sudo: required
services:
    - docker

before_install:
    - docker build -t jdchancellor/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jdchancellor/react-test npm test 

after_success:
    - docker build -t jdchancellor/multi-client ./client
    - docker build -t jdchancellor/multi-nginx ./nginx
    - docker build -t jdchancellor/multi-server ./server
    - docker build -t jdchancellor/multi-worker ./worker

    #login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #push images to docker hub
    - docker push jdchancellor/multi-client
    - docker push jdchancellor/multi-nginx
    - docker push jdchancellor/multi-server
    - docker push jdchancellor/multi-worker